# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'naimenovanja_tab_OPTIMIZED.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QGroupBox, QLabel,
    QLineEdit, QSizePolicy, QWidget)

class Ui_NaimenovanjaTab(object):
    def setupUi(self, NaimenovanjaTab):
        if not NaimenovanjaTab.objectName():
            NaimenovanjaTab.setObjectName(u"NaimenovanjaTab")
        NaimenovanjaTab.resize(1920, 1080)
        self.main_grid_frame = QFrame(NaimenovanjaTab)
        self.main_grid_frame.setObjectName(u"main_grid_frame")
        self.main_grid_frame.setGeometry(QRect(10, 0, 1000, 550))
        self.group_31 = QGroupBox(self.main_grid_frame)
        self.group_31.setObjectName(u"group_31")
        self.group_31.setGeometry(QRect(0, 0, 560, 380))
        self.V_31_44_pocetna = QFrame(self.group_31)
        self.V_31_44_pocetna.setObjectName(u"V_31_44_pocetna")
        self.V_31_44_pocetna.setGeometry(QRect(80, 0, 2, 550))
        self.V_31_44_pocetna.setFrameShape(QFrame.Shape.VLine)
        self.V_31_44_pocetna.setFrameShadow(QFrame.Shadow.Plain)
        self.V_31_44_pocetna.setLineWidth(1)
        self.lbl_rubrika31 = QLabel(self.group_31)
        self.lbl_rubrika31.setObjectName(u"lbl_rubrika31")
        self.lbl_rubrika31.setGeometry(QRect(5, 1, 75, 50))
        self.lbl_r31_oznake = QLabel(self.group_31)
        self.lbl_r31_oznake.setObjectName(u"lbl_r31_oznake")
        self.lbl_r31_oznake.setGeometry(QRect(85, -6, 211, 31))
        self.le_r31_oznake_br = QLineEdit(self.group_31)
        self.le_r31_oznake_br.setObjectName(u"le_r31_oznake_br")
        self.le_r31_oznake_br.setGeometry(QRect(144, 20, 401, 22))
        self.u_kont = QLabel(self.group_31)
        self.u_kont.setObjectName(u"u_kont")
        self.u_kont.setGeometry(QRect(85, 25, 47, 41))
        self.le_r31_paketa = QLineEdit(self.group_31)
        self.le_r31_paketa.setObjectName(u"le_r31_paketa")
        self.le_r31_paketa.setGeometry(QRect(144, 45, 401, 22))
        self.lbl_r31_vrsta = QLabel(self.group_31)
        self.lbl_r31_vrsta.setObjectName(u"lbl_r31_vrsta")
        self.lbl_r31_vrsta.setGeometry(QRect(85, 75, 48, 12))
        self.le_r31_broj = QLineEdit(self.group_31)
        self.le_r31_broj.setObjectName(u"le_r31_broj")
        self.le_r31_broj.setGeometry(QRect(144, 70, 45, 22))
        self.le_r31_vrsta = QLineEdit(self.group_31)
        self.le_r31_vrsta.setObjectName(u"le_r31_vrsta")
        self.le_r31_vrsta.setGeometry(QRect(195, 70, 50, 22))
        self.le_r31_vrsta_naziv = QLineEdit(self.group_31)
        self.le_r31_vrsta_naziv.setObjectName(u"le_r31_vrsta_naziv")
        self.le_r31_vrsta_naziv.setGeometry(QRect(280, 70, 265, 22))
        self.le_r31_vrsta_naziv.setReadOnly(False)
        self.lbl_r31_kontejner = QLabel(self.group_31)
        self.lbl_r31_kontejner.setObjectName(u"lbl_r31_kontejner")
        self.lbl_r31_kontejner.setGeometry(QRect(85, 98, 48, 12))
        self.le_r31_kontejner_1 = QLineEdit(self.group_31)
        self.le_r31_kontejner_1.setObjectName(u"le_r31_kontejner_1")
        self.le_r31_kontejner_1.setGeometry(QRect(144, 95, 171, 22))
        self.le_r31_kontejner_2 = QLineEdit(self.group_31)
        self.le_r31_kontejner_2.setObjectName(u"le_r31_kontejner_2")
        self.le_r31_kontejner_2.setGeometry(QRect(320, 95, 225, 22))
        self.te_r31_opis = QLineEdit(self.group_31)
        self.te_r31_opis.setObjectName(u"te_r31_opis")
        self.te_r31_opis.setGeometry(QRect(85, 125, 460, 22))
        self.te_r31_opis_2 = QLineEdit(self.group_31)
        self.te_r31_opis_2.setObjectName(u"te_r31_opis_2")
        self.te_r31_opis_2.setGeometry(QRect(85, 150, 460, 22))
        self.le_r31_trg_naziv = QLineEdit(self.group_31)
        self.le_r31_trg_naziv.setObjectName(u"le_r31_trg_naziv")
        self.le_r31_trg_naziv.setGeometry(QRect(85, 200, 460, 71))
        self.group_32_39 = QGroupBox(self.main_grid_frame)
        self.group_32_39.setObjectName(u"group_32_39")
        self.group_32_39.setGeometry(QRect(560, 0, 440, 180))
        self.V_32_kraj = QFrame(self.group_32_39)
        self.V_32_kraj.setObjectName(u"V_32_kraj")
        self.V_32_kraj.setGeometry(QRect(55, 0, 2, 60))
        self.V_32_kraj.setFrameShape(QFrame.Shape.VLine)
        self.V_32_kraj.setFrameShadow(QFrame.Shadow.Plain)
        self.V_32_kraj.setLineWidth(1)
        self.V_33_kraj = QFrame(self.group_32_39)
        self.V_33_kraj.setObjectName(u"V_33_kraj")
        self.V_33_kraj.setGeometry(QRect(200, 0, 2, 60))
        self.V_33_kraj.setFrameShape(QFrame.Shape.VLine)
        self.V_33_kraj.setFrameShadow(QFrame.Shadow.Plain)
        self.V_33_kraj.setLineWidth(1)
        self.V_podbroj_kraj = QFrame(self.group_32_39)
        self.V_podbroj_kraj.setObjectName(u"V_podbroj_kraj")
        self.V_podbroj_kraj.setGeometry(QRect(270, 0, 2, 60))
        self.V_podbroj_kraj.setFrameShape(QFrame.Shape.VLine)
        self.V_podbroj_kraj.setFrameShadow(QFrame.Shadow.Plain)
        self.V_podbroj_kraj.setLineWidth(1)
        self.V_34_kraj = QFrame(self.group_32_39)
        self.V_34_kraj.setObjectName(u"V_34_kraj")
        self.V_34_kraj.setGeometry(QRect(180, 60, 2, 120))
        self.V_34_kraj.setFrameShape(QFrame.Shape.VLine)
        self.V_34_kraj.setFrameShadow(QFrame.Shadow.Plain)
        self.V_34_kraj.setLineWidth(1)
        self.V_35_kraj = QFrame(self.group_32_39)
        self.V_35_kraj.setObjectName(u"V_35_kraj")
        self.V_35_kraj.setGeometry(QRect(310, 60, 2, 120))
        self.V_35_kraj.setFrameShape(QFrame.Shape.VLine)
        self.V_35_kraj.setFrameShadow(QFrame.Shadow.Plain)
        self.V_35_kraj.setLineWidth(1)
        self.H_r1 = QFrame(self.group_32_39)
        self.H_r1.setObjectName(u"H_r1")
        self.H_r1.setGeometry(QRect(0, 60, 440, 2))
        self.H_r1.setFrameShape(QFrame.Shape.HLine)
        self.H_r1.setFrameShadow(QFrame.Shadow.Plain)
        self.H_r1.setLineWidth(1)
        self.H_r2 = QFrame(self.group_32_39)
        self.H_r2.setObjectName(u"H_r2")
        self.H_r2.setGeometry(QRect(0, 120, 440, 2))
        self.H_r2.setFrameShape(QFrame.Shape.HLine)
        self.H_r2.setFrameShadow(QFrame.Shadow.Plain)
        self.H_r2.setLineWidth(1)
        self.lbl_rubrika32 = QLabel(self.group_32_39)
        self.lbl_rubrika32.setObjectName(u"lbl_rubrika32")
        self.lbl_rubrika32.setGeometry(QRect(5, 10, 45, 12))
        self.le_rubrika32 = QLineEdit(self.group_32_39)
        self.le_rubrika32.setObjectName(u"le_rubrika32")
        self.le_rubrika32.setGeometry(QRect(15, 26, 30, 25))
        self.lbl_rubrika33 = QLabel(self.group_32_39)
        self.lbl_rubrika33.setObjectName(u"lbl_rubrika33")
        self.lbl_rubrika33.setGeometry(QRect(60, 10, 100, 12))
        self.le_rubrika33 = QLineEdit(self.group_32_39)
        self.le_rubrika33.setObjectName(u"le_rubrika33")
        self.le_rubrika33.setGeometry(QRect(60, 26, 135, 25))
        self.le_rubrika33_podbroj = QLineEdit(self.group_32_39)
        self.le_rubrika33_podbroj.setObjectName(u"le_rubrika33_podbroj")
        self.le_rubrika33_podbroj.setGeometry(QRect(205, 26, 60, 25))
        self.lbl_rubrika34 = QLabel(self.group_32_39)
        self.lbl_rubrika34.setObjectName(u"lbl_rubrika34")
        self.lbl_rubrika34.setGeometry(QRect(5, 62, 120, 12))
        self.le_rubrika34_zemlja = QLineEdit(self.group_32_39)
        self.le_rubrika34_zemlja.setObjectName(u"le_rubrika34_zemlja")
        self.le_rubrika34_zemlja.setGeometry(QRect(15, 80, 45, 30))
        self.le_rubrika34_regija = QLineEdit(self.group_32_39)
        self.le_rubrika34_regija.setObjectName(u"le_rubrika34_regija")
        self.le_rubrika34_regija.setGeometry(QRect(80, 80, 45, 30))
        self.lbl_rubrika35 = QLabel(self.group_32_39)
        self.lbl_rubrika35.setObjectName(u"lbl_rubrika35")
        self.lbl_rubrika35.setGeometry(QRect(185, 62, 100, 12))
        self.le_rubrika35 = QLineEdit(self.group_32_39)
        self.le_rubrika35.setObjectName(u"le_rubrika35")
        self.le_rubrika35.setGeometry(QRect(185, 80, 120, 30))
        self.lbl_rubrika36 = QLabel(self.group_32_39)
        self.lbl_rubrika36.setObjectName(u"lbl_rubrika36")
        self.lbl_rubrika36.setGeometry(QRect(315, 62, 100, 12))
        self.le_rubrika36 = QLineEdit(self.group_32_39)
        self.le_rubrika36.setObjectName(u"le_rubrika36")
        self.le_rubrika36.setGeometry(QRect(315, 80, 120, 30))
        self.lbl_rubrika37 = QLabel(self.group_32_39)
        self.lbl_rubrika37.setObjectName(u"lbl_rubrika37")
        self.lbl_rubrika37.setGeometry(QRect(5, 122, 100, 12))
        self.le_rubrika37_1 = QLineEdit(self.group_32_39)
        self.le_rubrika37_1.setObjectName(u"le_rubrika37_1")
        self.le_rubrika37_1.setGeometry(QRect(10, 140, 45, 30))
        self.le_rubrika37_2 = QLineEdit(self.group_32_39)
        self.le_rubrika37_2.setObjectName(u"le_rubrika37_2")
        self.le_rubrika37_2.setGeometry(QRect(70, 140, 40, 30))
        self.lbl_rubrika38 = QLabel(self.group_32_39)
        self.lbl_rubrika38.setObjectName(u"lbl_rubrika38")
        self.lbl_rubrika38.setGeometry(QRect(185, 122, 100, 12))
        self.le_rubrika38 = QLineEdit(self.group_32_39)
        self.le_rubrika38.setObjectName(u"le_rubrika38")
        self.le_rubrika38.setGeometry(QRect(185, 140, 120, 30))
        self.lbl_rubrika39 = QLabel(self.group_32_39)
        self.lbl_rubrika39.setObjectName(u"lbl_rubrika39")
        self.lbl_rubrika39.setGeometry(QRect(315, 122, 100, 12))
        self.le_rubrika39 = QLineEdit(self.group_32_39)
        self.le_rubrika39.setObjectName(u"le_rubrika39")
        self.le_rubrika39.setGeometry(QRect(315, 140, 120, 30))
        self.group_40 = QGroupBox(self.main_grid_frame)
        self.group_40.setObjectName(u"group_40")
        self.group_40.setGeometry(QRect(560, 180, 440, 60))
        self.V_31_kraj = QFrame(self.group_40)
        self.V_31_kraj.setObjectName(u"V_31_kraj")
        self.V_31_kraj.setGeometry(QRect(0, -180, 2, 380))
        self.V_31_kraj.setFrameShape(QFrame.Shape.VLine)
        self.V_31_kraj.setFrameShadow(QFrame.Shadow.Plain)
        self.V_31_kraj.setLineWidth(1)
        self.H_r3 = QFrame(self.group_40)
        self.H_r3.setObjectName(u"H_r3")
        self.H_r3.setGeometry(QRect(0, 0, 440, 2))
        self.H_r3.setFrameShape(QFrame.Shape.HLine)
        self.H_r3.setFrameShadow(QFrame.Shadow.Plain)
        self.H_r3.setLineWidth(1)
        self.lbl_rubrika40 = QLabel(self.group_40)
        self.lbl_rubrika40.setObjectName(u"lbl_rubrika40")
        self.lbl_rubrika40.setGeometry(QRect(5, 10, 150, 12))
        self.le_rubrika40_1 = QLineEdit(self.group_40)
        self.le_rubrika40_1.setObjectName(u"le_rubrika40_1")
        self.le_rubrika40_1.setGeometry(QRect(5, 28, 30, 25))
        self.le_rubrika40_2 = QLineEdit(self.group_40)
        self.le_rubrika40_2.setObjectName(u"le_rubrika40_2")
        self.le_rubrika40_2.setGeometry(QRect(47, 28, 218, 25))
        self.le_rubrika40_3 = QLineEdit(self.group_40)
        self.le_rubrika40_3.setObjectName(u"le_rubrika40_3")
        self.le_rubrika40_3.setGeometry(QRect(277, 28, 158, 25))
        self.group_41_43 = QGroupBox(self.main_grid_frame)
        self.group_41_43.setObjectName(u"group_41_43")
        self.group_41_43.setGeometry(QRect(560, 240, 440, 140))
        self.V_41_kraj = QFrame(self.group_41_43)
        self.V_41_kraj.setObjectName(u"V_41_kraj")
        self.V_41_kraj.setGeometry(QRect(150, 0, 2, 140))
        self.V_41_kraj.setFrameShape(QFrame.Shape.VLine)
        self.V_41_kraj.setFrameShadow(QFrame.Shadow.Plain)
        self.V_41_kraj.setLineWidth(1)
        self.V_42_kraj = QFrame(self.group_41_43)
        self.V_42_kraj.setObjectName(u"V_42_kraj")
        self.V_42_kraj.setGeometry(QRect(300, 0, 2, 140))
        self.V_42_kraj.setFrameShape(QFrame.Shape.VLine)
        self.V_42_kraj.setFrameShadow(QFrame.Shadow.Plain)
        self.V_42_kraj.setLineWidth(1)
        self.V_43_kraj = QFrame(self.group_41_43)
        self.V_43_kraj.setObjectName(u"V_43_kraj")
        self.V_43_kraj.setGeometry(QRect(370, 0, 2, 140))
        self.V_43_kraj.setFrameShape(QFrame.Shape.VLine)
        self.V_43_kraj.setFrameShadow(QFrame.Shadow.Plain)
        self.V_43_kraj.setLineWidth(1)
        self.H_r4 = QFrame(self.group_41_43)
        self.H_r4.setObjectName(u"H_r4")
        self.H_r4.setGeometry(QRect(0, 0, 440, 2))
        self.H_r4.setFrameShape(QFrame.Shape.HLine)
        self.H_r4.setFrameShadow(QFrame.Shadow.Plain)
        self.H_r4.setLineWidth(1)
        self.lbl_rubrika41 = QLabel(self.group_41_43)
        self.lbl_rubrika41.setObjectName(u"lbl_rubrika41")
        self.lbl_rubrika41.setGeometry(QRect(5, 10, 130, 12))
        self.le_rubrika41 = QLineEdit(self.group_41_43)
        self.le_rubrika41.setObjectName(u"le_rubrika41")
        self.le_rubrika41.setGeometry(QRect(7, 27, 140, 30))
        self.lbl_rubrika42 = QLabel(self.group_41_43)
        self.lbl_rubrika42.setObjectName(u"lbl_rubrika42")
        self.lbl_rubrika42.setGeometry(QRect(160, 10, 130, 12))
        self.le_rubrika42 = QLineEdit(self.group_41_43)
        self.le_rubrika42.setObjectName(u"le_rubrika42")
        self.le_rubrika42.setGeometry(QRect(160, 28, 130, 30))
        self.lbl_rubrika43 = QLabel(self.group_41_43)
        self.lbl_rubrika43.setObjectName(u"lbl_rubrika43")
        self.lbl_rubrika43.setGeometry(QRect(305, 10, 20, 12))
        self.lbl_rubrika43_tekst = QLabel(self.group_41_43)
        self.lbl_rubrika43_tekst.setObjectName(u"lbl_rubrika43_tekst")
        self.lbl_rubrika43_tekst.setGeometry(QRect(330, 10, 35, 12))
        self.le_rubrika43 = QLineEdit(self.group_41_43)
        self.le_rubrika43.setObjectName(u"le_rubrika43")
        self.le_rubrika43.setGeometry(QRect(305, 28, 50, 30))
        self.group_44 = QGroupBox(self.main_grid_frame)
        self.group_44.setObjectName(u"group_44")
        self.group_44.setGeometry(QRect(0, 380, 760, 170))
        self.H_31_dno = QFrame(self.group_44)
        self.H_31_dno.setObjectName(u"H_31_dno")
        self.H_31_dno.setGeometry(QRect(0, 0, 1000, 2))
        self.H_31_dno.setFrameShape(QFrame.Shape.HLine)
        self.H_31_dno.setFrameShadow(QFrame.Shadow.Plain)
        self.H_31_dno.setLineWidth(1)
        self.lbl_rubrika44 = QLabel(self.group_44)
        self.lbl_rubrika44.setObjectName(u"lbl_rubrika44")
        self.lbl_rubrika44.setGeometry(QRect(5, 10, 75, 40))
        self.le_rubrika44_1 = QLineEdit(self.group_44)
        self.le_rubrika44_1.setObjectName(u"le_rubrika44_1")
        self.le_rubrika44_1.setGeometry(QRect(85, 15, 285, 24))
        self.le_rubrika44_1.setReadOnly(True)
        self.le_rubrika44_3 = QLineEdit(self.group_44)
        self.le_rubrika44_3.setObjectName(u"le_rubrika44_3")
        self.le_rubrika44_3.setGeometry(QRect(375, 15, 170, 24))
        self.le_rubrika44_4 = QLineEdit(self.group_44)
        self.le_rubrika44_4.setObjectName(u"le_rubrika44_4")
        self.le_rubrika44_4.setGeometry(QRect(85, 45, 220, 24))
        self.le_rubrika44_5 = QLineEdit(self.group_44)
        self.le_rubrika44_5.setObjectName(u"le_rubrika44_5")
        self.le_rubrika44_5.setGeometry(QRect(310, 45, 235, 24))
        self.group_45_46 = QGroupBox(self.main_grid_frame)
        self.group_45_46.setObjectName(u"group_45_46")
        self.group_45_46.setGeometry(QRect(760, 380, 240, 170))
        self.V_44_45_split = QFrame(self.group_45_46)
        self.V_44_45_split.setObjectName(u"V_44_45_split")
        self.V_44_45_split.setGeometry(QRect(0, 0, 2, 170))
        self.V_44_45_split.setFrameShape(QFrame.Shape.VLine)
        self.V_44_45_split.setFrameShadow(QFrame.Shadow.Plain)
        self.V_44_45_split.setLineWidth(1)
        self.V_45_sifra = QFrame(self.group_45_46)
        self.V_45_sifra.setObjectName(u"V_45_sifra")
        self.V_45_sifra.setGeometry(QRect(60, 0, 2, 70))
        self.V_45_sifra.setFrameShape(QFrame.Shape.VLine)
        self.V_45_sifra.setFrameShadow(QFrame.Shadow.Plain)
        self.V_45_sifra.setLineWidth(1)
        self.H_45_dno = QFrame(self.group_45_46)
        self.H_45_dno.setObjectName(u"H_45_dno")
        self.H_45_dno.setGeometry(QRect(0, 70, 240, 2))
        self.H_45_dno.setFrameShape(QFrame.Shape.HLine)
        self.H_45_dno.setFrameShadow(QFrame.Shadow.Plain)
        self.H_45_dno.setLineWidth(1)
        self.lbl_rubrika45 = QLabel(self.group_45_46)
        self.lbl_rubrika45.setObjectName(u"lbl_rubrika45")
        self.lbl_rubrika45.setGeometry(QRect(64, 10, 119, 12))
        self.le_rubrika45_sifra = QLineEdit(self.group_45_46)
        self.le_rubrika45_sifra.setObjectName(u"le_rubrika45_sifra")
        self.le_rubrika45_sifra.setGeometry(QRect(5, 23, 50, 25))
        self.le_rubrika45_iznos = QLineEdit(self.group_45_46)
        self.le_rubrika45_iznos.setObjectName(u"le_rubrika45_iznos")
        self.le_rubrika45_iznos.setGeometry(QRect(65, 23, 170, 25))
        self.lbl_rubrika46 = QLabel(self.group_45_46)
        self.lbl_rubrika46.setObjectName(u"lbl_rubrika46")
        self.lbl_rubrika46.setGeometry(QRect(5, 75, 120, 12))
        self.le_rubrika46 = QLineEdit(self.group_45_46)
        self.le_rubrika46.setObjectName(u"le_rubrika46")
        self.le_rubrika46.setGeometry(QRect(5, 90, 230, 30))
        self.status_bar_widget = QWidget(NaimenovanjaTab)
        self.status_bar_widget.setObjectName(u"status_bar_widget")
        self.status_bar_widget.setGeometry(QRect(10, 715, 1300, 55))
        self.lbl_status_total = QLabel(self.status_bar_widget)
        self.lbl_status_total.setObjectName(u"lbl_status_total")
        self.lbl_status_total.setGeometry(QRect(20, 12, 200, 30))
        self.lbl_status_items = QLabel(self.status_bar_widget)
        self.lbl_status_items.setObjectName(u"lbl_status_items")
        self.lbl_status_items.setGeometry(QRect(240, 12, 200, 30))
        self.lbl_status_bruto = QLabel(self.status_bar_widget)
        self.lbl_status_bruto.setObjectName(u"lbl_status_bruto")
        self.lbl_status_bruto.setGeometry(QRect(460, 12, 200, 30))
        self.lbl_status_netto = QLabel(self.status_bar_widget)
        self.lbl_status_netto.setObjectName(u"lbl_status_netto")
        self.lbl_status_netto.setGeometry(QRect(680, 12, 200, 30))
        self.lbl_status_validation = QLabel(self.status_bar_widget)
        self.lbl_status_validation.setObjectName(u"lbl_status_validation")
        self.lbl_status_validation.setGeometry(QRect(900, 12, 390, 30))

        self.retranslateUi(NaimenovanjaTab)

        QMetaObject.connectSlotsByName(NaimenovanjaTab)
    # setupUi

    def retranslateUi(self, NaimenovanjaTab):
        self.lbl_rubrika31.setText(QCoreApplication.translate("NaimenovanjaTab", u"31 Pakovanje i\n"
"opis\n"
"robe", None))
        self.lbl_r31_oznake.setText(QCoreApplication.translate("NaimenovanjaTab", u"Oznake i brojevi - broj vrsta pakata", None))
        self.u_kont.setText(QCoreApplication.translate("NaimenovanjaTab", u"Oznake i br.\n"
"pakata", None))
        self.lbl_r31_vrsta.setText(QCoreApplication.translate("NaimenovanjaTab", u"Broj i vrsta", None))
        self.le_r31_vrsta_naziv.setStyleSheet(QCoreApplication.translate("NaimenovanjaTab", u"background-color: #e3f2fd; border: 2px solid #2196f3; color: #1565c0; font-weight: bold;", None))
        self.lbl_r31_kontejner.setText(QCoreApplication.translate("NaimenovanjaTab", u"Kontejner", None))
        self.lbl_rubrika32.setText(QCoreApplication.translate("NaimenovanjaTab", u"32  naim.br", None))
        self.lbl_rubrika33.setText(QCoreApplication.translate("NaimenovanjaTab", u"33  \u0161ifra robe", None))
        self.lbl_rubrika34.setText(QCoreApplication.translate("NaimenovanjaTab", u"34  \u0161ifra zemlje porijekla", None))
        self.lbl_rubrika35.setText(QCoreApplication.translate("NaimenovanjaTab", u"35  brutto masa u kg", None))
        self.lbl_rubrika36.setText(QCoreApplication.translate("NaimenovanjaTab", u"36  povlastice", None))
        self.lbl_rubrika37.setText(QCoreApplication.translate("NaimenovanjaTab", u"37  postupak", None))
        self.lbl_rubrika38.setText(QCoreApplication.translate("NaimenovanjaTab", u"38  netto masa u kg", None))
        self.lbl_rubrika39.setText(QCoreApplication.translate("NaimenovanjaTab", u"39  kvote", None))
        self.lbl_rubrika40.setText(QCoreApplication.translate("NaimenovanjaTab", u"40  isprava / prethodni dokument", None))
        self.lbl_rubrika41.setText(QCoreApplication.translate("NaimenovanjaTab", u"41  dopunska jedinica", None))
        self.lbl_rubrika42.setText(QCoreApplication.translate("NaimenovanjaTab", u"42  cijena robe", None))
        self.lbl_rubrika43.setText(QCoreApplication.translate("NaimenovanjaTab", u"43  m.v.", None))
        self.lbl_rubrika43_tekst.setText(QCoreApplication.translate("NaimenovanjaTab", u"V.M.", None))
        self.lbl_rubrika44.setText(QCoreApplication.translate("NaimenovanjaTab", u"44 Prilo\u017eene\n"
"isprave", None))
        self.le_rubrika44_1.setPlaceholderText(QCoreApplication.translate("NaimenovanjaTab", u"P.D. kodovi (auto)", None))
        self.le_rubrika44_5.setPlaceholderText(QCoreApplication.translate("NaimenovanjaTab", u"dodatna napomena", None))
        self.lbl_rubrika45.setText(QCoreApplication.translate("NaimenovanjaTab", u"45  prilago\u0111enje", None))
        self.lbl_rubrika46.setText(QCoreApplication.translate("NaimenovanjaTab", u"46  statisti\u010dka vrijednost", None))
        self.status_bar_widget.setStyleSheet(QCoreApplication.translate("NaimenovanjaTab", u"background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"    stop:0 #d4edda, stop:1 #c3e6cb);\n"
"border-top: 2px solid #28a745;", None))
        self.lbl_status_total.setText(QCoreApplication.translate("NaimenovanjaTab", u"\U0001f4b0 Ukupno: 0.00 EUR", None))
        self.lbl_status_total.setStyleSheet(QCoreApplication.translate("NaimenovanjaTab", u"color: #155724; font-weight: 600; font-size: 16px;", None))
        self.lbl_status_items.setText(QCoreApplication.translate("NaimenovanjaTab", u"\U0001f4e6 Broj komada: 0", None))
        self.lbl_status_items.setStyleSheet(QCoreApplication.translate("NaimenovanjaTab", u"color: #155724; font-weight: 600; font-size: 16px;", None))
        self.lbl_status_bruto.setText(QCoreApplication.translate("NaimenovanjaTab", u"\u2696\ufe0f Bruto: 0.00 kg", None))
        self.lbl_status_bruto.setStyleSheet(QCoreApplication.translate("NaimenovanjaTab", u"color: #155724; font-weight: 600; font-size: 16px;", None))
        self.lbl_status_netto.setText(QCoreApplication.translate("NaimenovanjaTab", u"\U0001f4ca Netto: 0.00 kg", None))
        self.lbl_status_netto.setStyleSheet(QCoreApplication.translate("NaimenovanjaTab", u"color: #155724; font-weight: 600; font-size: 16px;", None))
        self.lbl_status_validation.setText(QCoreApplication.translate("NaimenovanjaTab", u"\u2705 Svi unosi validni", None))
        self.lbl_status_validation.setStyleSheet(QCoreApplication.translate("NaimenovanjaTab", u"color: #155724; font-weight: bold; font-size: 16px;", None))
        pass
    # retranslateUi

