# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'zaglavlje_tab.ui'
##
## Created by: Qt User Interface Compiler version 6.10.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QCheckBox, QFrame, QLabel,
    QLineEdit, QPushButton, QSizePolicy, QWidget)

class Ui_ZaglavljeTab(object):
    def setupUi(self, ZaglavljeTab):
        if not ZaglavljeTab.objectName():
            ZaglavljeTab.setObjectName(u"ZaglavljeTab")
        ZaglavljeTab.resize(1250, 700)
        self.btn_novi = QPushButton(ZaglavljeTab)
        self.btn_novi.setObjectName(u"btn_novi")
        self.btn_novi.setGeometry(QRect(65, 20, 75, 25))
        self.btn_otvori = QPushButton(ZaglavljeTab)
        self.btn_otvori.setObjectName(u"btn_otvori")
        self.btn_otvori.setGeometry(QRect(145, 20, 75, 25))
        self.btn_import = QPushButton(ZaglavljeTab)
        self.btn_import.setObjectName(u"btn_import")
        self.btn_import.setGeometry(QRect(225, 20, 85, 25))
        self.chk_direktan = QCheckBox(ZaglavljeTab)
        self.chk_direktan.setObjectName(u"chk_direktan")
        self.chk_direktan.setGeometry(QRect(315, 22, 130, 20))
        self.top_search = QLineEdit(ZaglavljeTab)
        self.top_search.setObjectName(u"top_search")
        self.top_search.setGeometry(QRect(450, 20, 110, 25))
        self.btn_snimi = QPushButton(ZaglavljeTab)
        self.btn_snimi.setObjectName(u"btn_snimi")
        self.btn_snimi.setGeometry(QRect(570, 20, 75, 25))
        self.btn_brisi_top = QPushButton(ZaglavljeTab)
        self.btn_brisi_top.setObjectName(u"btn_brisi_top")
        self.btn_brisi_top.setGeometry(QRect(650, 20, 75, 25))
        self.btn_export = QPushButton(ZaglavljeTab)
        self.btn_export.setObjectName(u"btn_export")
        self.btn_export.setGeometry(QRect(730, 20, 85, 25))
        self.top_num = QLineEdit(ZaglavljeTab)
        self.top_num.setObjectName(u"top_num")
        self.top_num.setGeometry(QRect(825, 20, 25, 25))
        self.lbl_max = QLabel(ZaglavljeTab)
        self.lbl_max.setObjectName(u"lbl_max")
        self.lbl_max.setGeometry(QRect(855, 15, 80, 30))
        self.btn_izlaz = QPushButton(ZaglavljeTab)
        self.btn_izlaz.setObjectName(u"btn_izlaz")
        self.btn_izlaz.setGeometry(QRect(945, 20, 75, 25))
        self.glavni_grid = QFrame(ZaglavljeTab)
        self.glavni_grid.setObjectName(u"glavni_grid")
        self.glavni_grid.setGeometry(QRect(10, 120, 1000, 550))
        self.V_line_1 = QFrame(self.glavni_grid)
        self.V_line_1.setObjectName(u"V_line_1")
        self.V_line_1.setGeometry(QRect(350, 0, 2, 550))
        self.V_line_1.setFrameShape(QFrame.Shape.VLine)
        self.V_line_1.setFrameShadow(QFrame.Shadow.Plain)
        self.V_line_1.setLineWidth(1)
        self.V_line_2 = QFrame(self.glavni_grid)
        self.V_line_2.setObjectName(u"V_line_2")
        self.V_line_2.setGeometry(QRect(675, 0, 2, 550))
        self.V_line_2.setFrameShape(QFrame.Shape.VLine)
        self.V_line_2.setFrameShadow(QFrame.Shadow.Plain)
        self.V_line_2.setLineWidth(1)
        self.L2 = QLabel(self.glavni_grid)
        self.L2.setObjectName(u"L2")
        self.L2.setGeometry(QRect(5, 2, 150, 12))
        self.I2_id = QLineEdit(self.glavni_grid)
        self.I2_id.setObjectName(u"I2_id")
        self.I2_id.setGeometry(QRect(190, 2, 150, 16))
        self.I2_r1 = QLineEdit(self.glavni_grid)
        self.I2_r1.setObjectName(u"I2_r1")
        self.I2_r1.setGeometry(QRect(10, 18, 330, 18))
        self.I2_r2 = QLineEdit(self.glavni_grid)
        self.I2_r2.setObjectName(u"I2_r2")
        self.I2_r2.setGeometry(QRect(10, 38, 330, 18))
        self.I2_r3 = QLineEdit(self.glavni_grid)
        self.I2_r3.setObjectName(u"I2_r3")
        self.I2_r3.setGeometry(QRect(10, 58, 330, 18))
        self.I2_r4 = QLineEdit(self.glavni_grid)
        self.I2_r4.setObjectName(u"I2_r4")
        self.I2_r4.setGeometry(QRect(10, 78, 330, 18))
        self.I2_r5 = QLineEdit(self.glavni_grid)
        self.I2_r5.setObjectName(u"I2_r5")
        self.I2_r5.setGeometry(QRect(10, 98, 330, 18))
        self.H2 = QFrame(self.glavni_grid)
        self.H2.setObjectName(u"H2")
        self.H2.setGeometry(QRect(0, 120, 350, 1))
        self.H2.setFrameShape(QFrame.Shape.HLine)
        self.L8 = QLabel(self.glavni_grid)
        self.L8.setObjectName(u"L8")
        self.L8.setGeometry(QRect(5, 122, 150, 12))
        self.I8_id = QLineEdit(self.glavni_grid)
        self.I8_id.setObjectName(u"I8_id")
        self.I8_id.setGeometry(QRect(190, 122, 150, 16))
        self.I8_r1 = QLineEdit(self.glavni_grid)
        self.I8_r1.setObjectName(u"I8_r1")
        self.I8_r1.setGeometry(QRect(10, 138, 330, 18))
        self.I8_r2 = QLineEdit(self.glavni_grid)
        self.I8_r2.setObjectName(u"I8_r2")
        self.I8_r2.setGeometry(QRect(10, 158, 330, 18))
        self.I8_r3 = QLineEdit(self.glavni_grid)
        self.I8_r3.setObjectName(u"I8_r3")
        self.I8_r3.setGeometry(QRect(10, 178, 330, 18))
        self.I8_r4 = QLineEdit(self.glavni_grid)
        self.I8_r4.setObjectName(u"I8_r4")
        self.I8_r4.setGeometry(QRect(10, 198, 330, 18))
        self.I8_r5 = QLineEdit(self.glavni_grid)
        self.I8_r5.setObjectName(u"I8_r5")
        self.I8_r5.setGeometry(QRect(10, 218, 330, 18))
        self.H8 = QFrame(self.glavni_grid)
        self.H8.setObjectName(u"H8")
        self.H8.setGeometry(QRect(0, 240, 350, 1))
        self.H8.setFrameShape(QFrame.Shape.HLine)
        self.L14 = QLabel(self.glavni_grid)
        self.L14.setObjectName(u"L14")
        self.L14.setGeometry(QRect(5, 242, 150, 12))
        self.I14_id = QLineEdit(self.glavni_grid)
        self.I14_id.setObjectName(u"I14_id")
        self.I14_id.setGeometry(QRect(190, 242, 150, 16))
        self.I14_r1 = QLineEdit(self.glavni_grid)
        self.I14_r1.setObjectName(u"I14_r1")
        self.I14_r1.setGeometry(QRect(10, 258, 330, 18))
        self.H14 = QFrame(self.glavni_grid)
        self.H14.setObjectName(u"H14")
        self.H14.setGeometry(QRect(0, 280, 350, 1))
        self.H14.setFrameShape(QFrame.Shape.HLine)
        self.L18 = QLabel(self.glavni_grid)
        self.L18.setObjectName(u"L18")
        self.L18.setGeometry(QRect(5, 282, 280, 12))
        self.I18 = QLineEdit(self.glavni_grid)
        self.I18.setObjectName(u"I18")
        self.I18.setGeometry(QRect(10, 296, 270, 18))
        self.L19 = QLabel(self.glavni_grid)
        self.L19.setObjectName(u"L19")
        self.L19.setGeometry(QRect(290, 282, 50, 12))
        self.I19 = QLineEdit(self.glavni_grid)
        self.I19.setObjectName(u"I19")
        self.I19.setGeometry(QRect(290, 296, 50, 18))
        self.H19 = QFrame(self.glavni_grid)
        self.H19.setObjectName(u"H19")
        self.H19.setGeometry(QRect(0, 318, 350, 1))
        self.H19.setFrameShape(QFrame.Shape.HLine)
        self.L21 = QLabel(self.glavni_grid)
        self.L21.setObjectName(u"L21")
        self.L21.setGeometry(QRect(5, 320, 340, 12))
        self.I21 = QLineEdit(self.glavni_grid)
        self.I21.setObjectName(u"I21")
        self.I21.setGeometry(QRect(10, 334, 330, 18))
        self.H21 = QFrame(self.glavni_grid)
        self.H21.setObjectName(u"H21")
        self.H21.setGeometry(QRect(0, 356, 350, 1))
        self.H21.setFrameShape(QFrame.Shape.HLine)
        self.L25 = QLabel(self.glavni_grid)
        self.L25.setObjectName(u"L25")
        self.L25.setGeometry(QRect(5, 358, 80, 12))
        self.I25 = QLineEdit(self.glavni_grid)
        self.I25.setObjectName(u"I25")
        self.I25.setGeometry(QRect(10, 372, 70, 18))
        self.L26 = QLabel(self.glavni_grid)
        self.L26.setObjectName(u"L26")
        self.L26.setGeometry(QRect(90, 358, 80, 12))
        self.I26 = QLineEdit(self.glavni_grid)
        self.I26.setObjectName(u"I26")
        self.I26.setGeometry(QRect(90, 372, 70, 18))
        self.L27 = QLabel(self.glavni_grid)
        self.L27.setObjectName(u"L27")
        self.L27.setGeometry(QRect(170, 358, 170, 12))
        self.I27 = QLineEdit(self.glavni_grid)
        self.I27.setObjectName(u"I27")
        self.I27.setGeometry(QRect(170, 372, 170, 18))
        self.H27 = QFrame(self.glavni_grid)
        self.H27.setObjectName(u"H27")
        self.H27.setGeometry(QRect(0, 394, 350, 1))
        self.H27.setFrameShape(QFrame.Shape.HLine)
        self.L29 = QLabel(self.glavni_grid)
        self.L29.setObjectName(u"L29")
        self.L29.setGeometry(QRect(5, 396, 165, 12))
        self.I29 = QLineEdit(self.glavni_grid)
        self.I29.setObjectName(u"I29")
        self.I29.setGeometry(QRect(10, 410, 160, 18))
        self.L30 = QLabel(self.glavni_grid)
        self.L30.setObjectName(u"L30")
        self.L30.setGeometry(QRect(180, 396, 165, 12))
        self.I30 = QLineEdit(self.glavni_grid)
        self.I30.setObjectName(u"I30")
        self.I30.setGeometry(QRect(180, 410, 160, 18))
        self.L1 = QLabel(self.glavni_grid)
        self.L1.setObjectName(u"L1")
        self.L1.setGeometry(QRect(355, 2, 100, 12))
        self.I1_1 = QLineEdit(self.glavni_grid)
        self.I1_1.setObjectName(u"I1_1")
        self.I1_1.setGeometry(QRect(355, 15, 30, 18))
        self.I1_2 = QLineEdit(self.glavni_grid)
        self.I1_2.setObjectName(u"I1_2")
        self.I1_2.setGeometry(QRect(390, 15, 30, 18))
        self.I1_3 = QLineEdit(self.glavni_grid)
        self.I1_3.setObjectName(u"I1_3")
        self.I1_3.setGeometry(QRect(425, 15, 30, 18))
        self.Hm1 = QFrame(self.glavni_grid)
        self.Hm1.setObjectName(u"Hm1")
        self.Hm1.setGeometry(QRect(350, 36, 325, 1))
        self.Hm1.setFrameShape(QFrame.Shape.HLine)
        self.L3 = QLabel(self.glavni_grid)
        self.L3.setObjectName(u"L3")
        self.L3.setGeometry(QRect(355, 40, 60, 12))
        self.I3_1 = QLineEdit(self.glavni_grid)
        self.I3_1.setObjectName(u"I3_1")
        self.I3_1.setGeometry(QRect(355, 53, 25, 18))
        self.I3_2 = QLineEdit(self.glavni_grid)
        self.I3_2.setObjectName(u"I3_2")
        self.I3_2.setGeometry(QRect(385, 53, 25, 18))
        self.L4 = QLabel(self.glavni_grid)
        self.L4.setObjectName(u"L4")
        self.L4.setGeometry(QRect(425, 40, 240, 12))
        self.I4 = QLineEdit(self.glavni_grid)
        self.I4.setObjectName(u"I4")
        self.I4.setGeometry(QRect(425, 53, 240, 18))
        self.Hm2 = QFrame(self.glavni_grid)
        self.Hm2.setObjectName(u"Hm2")
        self.Hm2.setGeometry(QRect(350, 75, 325, 1))
        self.Hm2.setFrameShape(QFrame.Shape.HLine)
        self.L5 = QLabel(self.glavni_grid)
        self.L5.setObjectName(u"L5")
        self.L5.setGeometry(QRect(355, 77, 60, 12))
        self.I5 = QLineEdit(self.glavni_grid)
        self.I5.setObjectName(u"I5")
        self.I5.setGeometry(QRect(355, 90, 40, 18))
        self.L6 = QLabel(self.glavni_grid)
        self.L6.setObjectName(u"L6")
        self.L6.setGeometry(QRect(405, 77, 80, 12))
        self.I6 = QLineEdit(self.glavni_grid)
        self.I6.setObjectName(u"I6")
        self.I6.setGeometry(QRect(405, 90, 80, 18))
        self.L7 = QLabel(self.glavni_grid)
        self.L7.setObjectName(u"L7")
        self.L7.setGeometry(QRect(495, 77, 170, 12))
        self.I7 = QLineEdit(self.glavni_grid)
        self.I7.setObjectName(u"I7")
        self.I7.setGeometry(QRect(495, 90, 170, 18))
        self.Hm3 = QFrame(self.glavni_grid)
        self.Hm3.setObjectName(u"Hm3")
        self.Hm3.setGeometry(QRect(350, 112, 325, 1))
        self.Hm3.setFrameShape(QFrame.Shape.HLine)
        self.L9 = QLabel(self.glavni_grid)
        self.L9.setObjectName(u"L9")
        self.L9.setGeometry(QRect(355, 114, 310, 12))
        self.I9_1 = QLineEdit(self.glavni_grid)
        self.I9_1.setObjectName(u"I9_1")
        self.I9_1.setGeometry(QRect(355, 127, 40, 18))
        self.I9_2 = QLineEdit(self.glavni_grid)
        self.I9_2.setObjectName(u"I9_2")
        self.I9_2.setGeometry(QRect(400, 127, 85, 18))
        self.I9_3 = QLineEdit(self.glavni_grid)
        self.I9_3.setObjectName(u"I9_3")
        self.I9_3.setGeometry(QRect(490, 127, 85, 18))
        self.I9_4 = QLineEdit(self.glavni_grid)
        self.I9_4.setObjectName(u"I9_4")
        self.I9_4.setGeometry(QRect(580, 127, 85, 18))
        self.Hm4 = QFrame(self.glavni_grid)
        self.Hm4.setObjectName(u"Hm4")
        self.Hm4.setGeometry(QRect(350, 149, 325, 1))
        self.Hm4.setFrameShape(QFrame.Shape.HLine)
        self.L10 = QLabel(self.glavni_grid)
        self.L10.setObjectName(u"L10")
        self.L10.setGeometry(QRect(355, 151, 75, 12))
        self.I10 = QLineEdit(self.glavni_grid)
        self.I10.setObjectName(u"I10")
        self.I10.setGeometry(QRect(355, 164, 75, 18))
        self.L11 = QLabel(self.glavni_grid)
        self.L11.setObjectName(u"L11")
        self.L11.setGeometry(QRect(435, 151, 75, 12))
        self.I11 = QLineEdit(self.glavni_grid)
        self.I11.setObjectName(u"I11")
        self.I11.setGeometry(QRect(435, 164, 75, 18))
        self.L12 = QLabel(self.glavni_grid)
        self.L12.setObjectName(u"L12")
        self.L12.setGeometry(QRect(515, 151, 75, 12))
        self.I12 = QLineEdit(self.glavni_grid)
        self.I12.setObjectName(u"I12")
        self.I12.setGeometry(QRect(515, 164, 75, 18))
        self.L13 = QLabel(self.glavni_grid)
        self.L13.setObjectName(u"L13")
        self.L13.setGeometry(QRect(595, 151, 75, 12))
        self.I13 = QLineEdit(self.glavni_grid)
        self.I13.setObjectName(u"I13")
        self.I13.setGeometry(QRect(595, 164, 70, 18))
        self.Hm5 = QFrame(self.glavni_grid)
        self.Hm5.setObjectName(u"Hm5")
        self.Hm5.setGeometry(QRect(350, 186, 325, 1))
        self.Hm5.setFrameShape(QFrame.Shape.HLine)
        self.L15_s = QLabel(self.glavni_grid)
        self.L15_s.setObjectName(u"L15_s")
        self.L15_s.setGeometry(QRect(355, 188, 100, 12))
        self.I15_naziv = QLineEdit(self.glavni_grid)
        self.I15_naziv.setObjectName(u"I15_naziv")
        self.I15_naziv.setGeometry(QRect(355, 201, 140, 18))
        self.L15_sifra = QLabel(self.glavni_grid)
        self.L15_sifra.setObjectName(u"L15_sifra")
        self.L15_sifra.setGeometry(QRect(500, 188, 50, 12))
        self.I15_sifra = QLineEdit(self.glavni_grid)
        self.I15_sifra.setObjectName(u"I15_sifra")
        self.I15_sifra.setGeometry(QRect(500, 201, 40, 18))
        self.L17_sifra_naslov = QLabel(self.glavni_grid)
        self.L17_sifra_naslov.setObjectName(u"L17_sifra_naslov")
        self.L17_sifra_naslov.setGeometry(QRect(550, 188, 50, 12))
        self.I17_sifra = QLineEdit(self.glavni_grid)
        self.I17_sifra.setObjectName(u"I17_sifra")
        self.I17_sifra.setGeometry(QRect(550, 201, 40, 18))
        self.Hm6 = QFrame(self.glavni_grid)
        self.Hm6.setObjectName(u"Hm6")
        self.Hm6.setGeometry(QRect(350, 223, 325, 1))
        self.Hm6.setFrameShape(QFrame.Shape.HLine)
        self.L16 = QLabel(self.glavni_grid)
        self.L16.setObjectName(u"L16")
        self.L16.setGeometry(QRect(355, 225, 140, 12))
        self.I16 = QLineEdit(self.glavni_grid)
        self.I16.setObjectName(u"I16")
        self.I16.setGeometry(QRect(355, 238, 140, 18))
        self.L17_drzava = QLabel(self.glavni_grid)
        self.L17_drzava.setObjectName(u"L17_drzava")
        self.L17_drzava.setGeometry(QRect(500, 225, 140, 12))
        self.I17_n = QLineEdit(self.glavni_grid)
        self.I17_n.setObjectName(u"I17_n")
        self.I17_n.setGeometry(QRect(500, 238, 140, 18))
        self.Hm7 = QFrame(self.glavni_grid)
        self.Hm7.setObjectName(u"Hm7")
        self.Hm7.setGeometry(QRect(350, 260, 325, 1))
        self.Hm7.setFrameShape(QFrame.Shape.HLine)
        self.L20 = QLabel(self.glavni_grid)
        self.L20.setObjectName(u"L20")
        self.L20.setGeometry(QRect(355, 262, 200, 12))
        self.I20_1 = QLineEdit(self.glavni_grid)
        self.I20_1.setObjectName(u"I20_1")
        self.I20_1.setGeometry(QRect(355, 275, 50, 18))
        self.I20_2 = QLineEdit(self.glavni_grid)
        self.I20_2.setObjectName(u"I20_2")
        self.I20_2.setGeometry(QRect(410, 275, 200, 18))
        self.Hm8 = QFrame(self.glavni_grid)
        self.Hm8.setObjectName(u"Hm8")
        self.Hm8.setGeometry(QRect(350, 298, 325, 1))
        self.Hm8.setFrameShape(QFrame.Shape.HLine)
        self.L22 = QLabel(self.glavni_grid)
        self.L22.setObjectName(u"L22")
        self.L22.setGeometry(QRect(355, 300, 100, 12))
        self.I22_val = QLineEdit(self.glavni_grid)
        self.I22_val.setObjectName(u"I22_val")
        self.I22_val.setGeometry(QRect(355, 313, 40, 18))
        self.I22_iznos = QLineEdit(self.glavni_grid)
        self.I22_iznos.setObjectName(u"I22_iznos")
        self.I22_iznos.setGeometry(QRect(400, 313, 60, 18))
        self.L23 = QLabel(self.glavni_grid)
        self.L23.setObjectName(u"L23")
        self.L23.setGeometry(QRect(465, 300, 80, 12))
        self.I23 = QLineEdit(self.glavni_grid)
        self.I23.setObjectName(u"I23")
        self.I23.setGeometry(QRect(465, 313, 80, 18))
        self.L24 = QLabel(self.glavni_grid)
        self.L24.setObjectName(u"L24")
        self.L24.setGeometry(QRect(555, 300, 100, 12))
        self.I24_1 = QLineEdit(self.glavni_grid)
        self.I24_1.setObjectName(u"I24_1")
        self.I24_1.setGeometry(QRect(555, 313, 30, 18))
        self.I24_2 = QLineEdit(self.glavni_grid)
        self.I24_2.setObjectName(u"I24_2")
        self.I24_2.setGeometry(QRect(590, 313, 30, 18))
        self.Hm9 = QFrame(self.glavni_grid)
        self.Hm9.setObjectName(u"Hm9")
        self.Hm9.setGeometry(QRect(350, 335, 325, 1))
        self.Hm9.setFrameShape(QFrame.Shape.HLine)
        self.I_tr_1 = QLineEdit(self.glavni_grid)
        self.I_tr_1.setObjectName(u"I_tr_1")
        self.I_tr_1.setGeometry(QRect(355, 340, 60, 18))
        self.I_tr_1.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.L_tr_1 = QLabel(self.glavni_grid)
        self.L_tr_1.setObjectName(u"L_tr_1")
        self.L_tr_1.setGeometry(QRect(420, 338, 180, 26))
        font = QFont()
        font.setPointSize(20)
        self.L_tr_1.setFont(font)
        self.L_brutto = QLabel(self.glavni_grid)
        self.L_brutto.setObjectName(u"L_brutto")
        self.L_brutto.setGeometry(QRect(560, 343, 40, 12))
        self.I_brutto = QLineEdit(self.glavni_grid)
        self.I_brutto.setObjectName(u"I_brutto")
        self.I_brutto.setGeometry(QRect(600, 340, 70, 18))
        self.I_tr_2 = QLineEdit(self.glavni_grid)
        self.I_tr_2.setObjectName(u"I_tr_2")
        self.I_tr_2.setGeometry(QRect(355, 360, 60, 18))
        self.I_tr_2.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.L_tr_2 = QLabel(self.glavni_grid)
        self.L_tr_2.setObjectName(u"L_tr_2")
        self.L_tr_2.setGeometry(QRect(420, 358, 180, 26))
        self.L_tr_2.setFont(font)
        self.I_tr_3 = QLineEdit(self.glavni_grid)
        self.I_tr_3.setObjectName(u"I_tr_3")
        self.I_tr_3.setGeometry(QRect(355, 380, 60, 18))
        self.I_tr_3.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.L_tr_3 = QLabel(self.glavni_grid)
        self.L_tr_3.setObjectName(u"L_tr_3")
        self.L_tr_3.setGeometry(QRect(420, 378, 180, 26))
        self.L_tr_3.setFont(font)
        self.L_netto = QLabel(self.glavni_grid)
        self.L_netto.setObjectName(u"L_netto")
        self.L_netto.setGeometry(QRect(560, 383, 40, 12))
        self.I_netto = QLineEdit(self.glavni_grid)
        self.I_netto.setObjectName(u"I_netto")
        self.I_netto.setGeometry(QRect(600, 380, 70, 18))
        self.I_tr_4 = QLineEdit(self.glavni_grid)
        self.I_tr_4.setObjectName(u"I_tr_4")
        self.I_tr_4.setGeometry(QRect(355, 400, 60, 18))
        self.I_tr_4.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.L_tr_4 = QLabel(self.glavni_grid)
        self.L_tr_4.setObjectName(u"L_tr_4")
        self.L_tr_4.setGeometry(QRect(420, 398, 180, 26))
        self.L_tr_4.setFont(font)
        self.I_tr_5 = QLineEdit(self.glavni_grid)
        self.I_tr_5.setObjectName(u"I_tr_5")
        self.I_tr_5.setGeometry(QRect(355, 420, 60, 18))
        self.I_tr_5.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)
        self.L_tr_5 = QLabel(self.glavni_grid)
        self.L_tr_5.setObjectName(u"L_tr_5")
        self.L_tr_5.setGeometry(QRect(420, 418, 180, 26))
        self.L_tr_5.setFont(font)
        self.L_radni = QLabel(self.glavni_grid)
        self.L_radni.setObjectName(u"L_radni")
        self.L_radni.setGeometry(QRect(560, 418, 50, 20))
        self.I_radni = QLineEdit(self.glavni_grid)
        self.I_radni.setObjectName(u"I_radni")
        self.I_radni.setGeometry(QRect(610, 420, 60, 18))
        self.Hm10 = QFrame(self.glavni_grid)
        self.Hm10.setObjectName(u"Hm10")
        self.Hm10.setGeometry(QRect(350, 445, 325, 1))
        self.Hm10.setFrameShape(QFrame.Shape.HLine)
        self.L48 = QLabel(self.glavni_grid)
        self.L48.setObjectName(u"L48")
        self.L48.setGeometry(QRect(355, 447, 130, 12))
        self.I48 = QLineEdit(self.glavni_grid)
        self.I48.setObjectName(u"I48")
        self.I48.setGeometry(QRect(355, 460, 130, 18))
        self.L49 = QLabel(self.glavni_grid)
        self.L49.setObjectName(u"L49")
        self.L49.setGeometry(QRect(495, 447, 170, 12))
        self.I49 = QLineEdit(self.glavni_grid)
        self.I49.setObjectName(u"I49")
        self.I49.setGeometry(QRect(495, 460, 175, 18))
        self.L_pr_sifra = QLabel(self.glavni_grid)
        self.L_pr_sifra.setObjectName(u"L_pr_sifra")
        self.L_pr_sifra.setGeometry(QRect(680, 10, 50, 20))
        self.L_pr_naziv = QLabel(self.glavni_grid)
        self.L_pr_naziv.setObjectName(u"L_pr_naziv")
        self.L_pr_naziv.setGeometry(QRect(729, 10, 190, 20))
        self.L_pr_datum = QLabel(self.glavni_grid)
        self.L_pr_datum.setObjectName(u"L_pr_datum")
        self.L_pr_datum.setGeometry(QRect(918, 10, 77, 20))
        self.I_pr_sifra_1 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_1.setObjectName(u"I_pr_sifra_1")
        self.I_pr_sifra_1.setGeometry(QRect(680, 30, 50, 20))
        self.I_pr_naziv_1 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_1.setObjectName(u"I_pr_naziv_1")
        self.I_pr_naziv_1.setGeometry(QRect(729, 30, 190, 20))
        self.I_pr_datum_1 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_1.setObjectName(u"I_pr_datum_1")
        self.I_pr_datum_1.setGeometry(QRect(918, 30, 77, 20))
        self.I_pr_sifra_2 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_2.setObjectName(u"I_pr_sifra_2")
        self.I_pr_sifra_2.setGeometry(QRect(680, 49, 50, 20))
        self.I_pr_naziv_2 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_2.setObjectName(u"I_pr_naziv_2")
        self.I_pr_naziv_2.setGeometry(QRect(729, 49, 190, 20))
        self.I_pr_datum_2 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_2.setObjectName(u"I_pr_datum_2")
        self.I_pr_datum_2.setGeometry(QRect(918, 49, 77, 20))
        self.I_pr_sifra_3 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_3.setObjectName(u"I_pr_sifra_3")
        self.I_pr_sifra_3.setGeometry(QRect(680, 68, 50, 20))
        self.I_pr_naziv_3 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_3.setObjectName(u"I_pr_naziv_3")
        self.I_pr_naziv_3.setGeometry(QRect(729, 68, 190, 20))
        self.I_pr_datum_3 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_3.setObjectName(u"I_pr_datum_3")
        self.I_pr_datum_3.setGeometry(QRect(918, 68, 77, 20))
        self.I_pr_sifra_4 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_4.setObjectName(u"I_pr_sifra_4")
        self.I_pr_sifra_4.setGeometry(QRect(680, 87, 50, 20))
        self.I_pr_naziv_4 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_4.setObjectName(u"I_pr_naziv_4")
        self.I_pr_naziv_4.setGeometry(QRect(729, 87, 190, 20))
        self.I_pr_datum_4 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_4.setObjectName(u"I_pr_datum_4")
        self.I_pr_datum_4.setGeometry(QRect(918, 87, 77, 20))
        self.I_pr_sifra_5 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_5.setObjectName(u"I_pr_sifra_5")
        self.I_pr_sifra_5.setGeometry(QRect(680, 106, 50, 20))
        self.I_pr_naziv_5 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_5.setObjectName(u"I_pr_naziv_5")
        self.I_pr_naziv_5.setGeometry(QRect(729, 106, 190, 20))
        self.I_pr_datum_5 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_5.setObjectName(u"I_pr_datum_5")
        self.I_pr_datum_5.setGeometry(QRect(918, 106, 77, 20))
        self.I_pr_sifra_6 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_6.setObjectName(u"I_pr_sifra_6")
        self.I_pr_sifra_6.setGeometry(QRect(680, 125, 50, 20))
        self.I_pr_naziv_6 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_6.setObjectName(u"I_pr_naziv_6")
        self.I_pr_naziv_6.setGeometry(QRect(729, 125, 190, 20))
        self.I_pr_datum_6 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_6.setObjectName(u"I_pr_datum_6")
        self.I_pr_datum_6.setGeometry(QRect(918, 125, 77, 20))
        self.I_pr_sifra_7 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_7.setObjectName(u"I_pr_sifra_7")
        self.I_pr_sifra_7.setGeometry(QRect(680, 144, 50, 20))
        self.I_pr_naziv_7 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_7.setObjectName(u"I_pr_naziv_7")
        self.I_pr_naziv_7.setGeometry(QRect(729, 144, 190, 20))
        self.I_pr_datum_7 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_7.setObjectName(u"I_pr_datum_7")
        self.I_pr_datum_7.setGeometry(QRect(918, 144, 77, 20))
        self.I_pr_sifra_8 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_8.setObjectName(u"I_pr_sifra_8")
        self.I_pr_sifra_8.setGeometry(QRect(680, 163, 50, 20))
        self.I_pr_naziv_8 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_8.setObjectName(u"I_pr_naziv_8")
        self.I_pr_naziv_8.setGeometry(QRect(729, 163, 190, 20))
        self.I_pr_datum_8 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_8.setObjectName(u"I_pr_datum_8")
        self.I_pr_datum_8.setGeometry(QRect(918, 163, 77, 20))
        self.I_pr_sifra_9 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_9.setObjectName(u"I_pr_sifra_9")
        self.I_pr_sifra_9.setGeometry(QRect(680, 182, 50, 20))
        self.I_pr_naziv_9 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_9.setObjectName(u"I_pr_naziv_9")
        self.I_pr_naziv_9.setGeometry(QRect(729, 182, 190, 20))
        self.I_pr_datum_9 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_9.setObjectName(u"I_pr_datum_9")
        self.I_pr_datum_9.setGeometry(QRect(918, 182, 77, 20))
        self.I_pr_sifra_10 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_10.setObjectName(u"I_pr_sifra_10")
        self.I_pr_sifra_10.setGeometry(QRect(680, 201, 50, 20))
        self.I_pr_naziv_10 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_10.setObjectName(u"I_pr_naziv_10")
        self.I_pr_naziv_10.setGeometry(QRect(729, 201, 190, 20))
        self.I_pr_datum_10 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_10.setObjectName(u"I_pr_datum_10")
        self.I_pr_datum_10.setGeometry(QRect(918, 201, 77, 20))
        self.I_pr_sifra_11 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_11.setObjectName(u"I_pr_sifra_11")
        self.I_pr_sifra_11.setGeometry(QRect(680, 220, 50, 20))
        self.I_pr_naziv_11 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_11.setObjectName(u"I_pr_naziv_11")
        self.I_pr_naziv_11.setGeometry(QRect(729, 220, 190, 20))
        self.I_pr_datum_11 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_11.setObjectName(u"I_pr_datum_11")
        self.I_pr_datum_11.setGeometry(QRect(918, 220, 77, 20))
        self.I_pr_sifra_12 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_12.setObjectName(u"I_pr_sifra_12")
        self.I_pr_sifra_12.setGeometry(QRect(680, 239, 50, 20))
        self.I_pr_naziv_12 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_12.setObjectName(u"I_pr_naziv_12")
        self.I_pr_naziv_12.setGeometry(QRect(729, 239, 190, 20))
        self.I_pr_datum_12 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_12.setObjectName(u"I_pr_datum_12")
        self.I_pr_datum_12.setGeometry(QRect(918, 239, 77, 20))
        self.I_pr_sifra_13 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_13.setObjectName(u"I_pr_sifra_13")
        self.I_pr_sifra_13.setGeometry(QRect(680, 258, 50, 20))
        self.I_pr_naziv_13 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_13.setObjectName(u"I_pr_naziv_13")
        self.I_pr_naziv_13.setGeometry(QRect(729, 258, 190, 20))
        self.I_pr_datum_13 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_13.setObjectName(u"I_pr_datum_13")
        self.I_pr_datum_13.setGeometry(QRect(918, 258, 77, 20))
        self.I_pr_sifra_14 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_14.setObjectName(u"I_pr_sifra_14")
        self.I_pr_sifra_14.setGeometry(QRect(680, 277, 50, 20))
        self.I_pr_naziv_14 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_14.setObjectName(u"I_pr_naziv_14")
        self.I_pr_naziv_14.setGeometry(QRect(729, 277, 190, 20))
        self.I_pr_datum_14 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_14.setObjectName(u"I_pr_datum_14")
        self.I_pr_datum_14.setGeometry(QRect(918, 277, 77, 20))
        self.I_pr_sifra_15 = QLineEdit(self.glavni_grid)
        self.I_pr_sifra_15.setObjectName(u"I_pr_sifra_15")
        self.I_pr_sifra_15.setGeometry(QRect(680, 296, 50, 20))
        self.I_pr_naziv_15 = QLineEdit(self.glavni_grid)
        self.I_pr_naziv_15.setObjectName(u"I_pr_naziv_15")
        self.I_pr_naziv_15.setGeometry(QRect(729, 296, 190, 20))
        self.I_pr_datum_15 = QLineEdit(self.glavni_grid)
        self.I_pr_datum_15.setObjectName(u"I_pr_datum_15")
        self.I_pr_datum_15.setGeometry(QRect(918, 296, 77, 20))

        self.retranslateUi(ZaglavljeTab)

        QMetaObject.connectSlotsByName(ZaglavljeTab)
    # setupUi

    def retranslateUi(self, ZaglavljeTab):
        self.btn_novi.setText(QCoreApplication.translate("ZaglavljeTab", u"novi", None))
        self.btn_otvori.setText(QCoreApplication.translate("ZaglavljeTab", u"otvori", None))
        self.btn_import.setText(QCoreApplication.translate("ZaglavljeTab", u"import JCI", None))
        self.chk_direktan.setText(QCoreApplication.translate("ZaglavljeTab", u"direktan unos naimenovanja", None))
        self.btn_snimi.setText(QCoreApplication.translate("ZaglavljeTab", u"snimi", None))
        self.btn_brisi_top.setText(QCoreApplication.translate("ZaglavljeTab", u"bri\u0161i", None))
        self.btn_export.setText(QCoreApplication.translate("ZaglavljeTab", u"export u AW", None))
        self.top_num.setText(QCoreApplication.translate("ZaglavljeTab", u"99", None))
        self.lbl_max.setText(QCoreApplication.translate("ZaglavljeTab", u"max broj\n"
"naim po JCI", None))
        self.btn_izlaz.setText(QCoreApplication.translate("ZaglavljeTab", u"izlaz", None))
        self.L2.setText(QCoreApplication.translate("ZaglavljeTab", u"2 Izvoznik / Po\u0161iljalac", None))
        self.L8.setText(QCoreApplication.translate("ZaglavljeTab", u"8 Primalac", None))
        self.L14.setText(QCoreApplication.translate("ZaglavljeTab", u"14 Deklarant / Zastupnik", None))
        self.L18.setText(QCoreApplication.translate("ZaglavljeTab", u"18 Identitet transp. sredstva", None))
        self.L19.setText(QCoreApplication.translate("ZaglavljeTab", u"19 Kont.", None))
        self.L21.setText(QCoreApplication.translate("ZaglavljeTab", u"21 Aktivno transp. sredstvo na granici", None))
        self.L25.setText(QCoreApplication.translate("ZaglavljeTab", u"25 Vid unutra", None))
        self.L26.setText(QCoreApplication.translate("ZaglavljeTab", u"26 Vid granica", None))
        self.L27.setText(QCoreApplication.translate("ZaglavljeTab", u"27 Mjesto utovara", None))
        self.L29.setText(QCoreApplication.translate("ZaglavljeTab", u"29 Izlazna carinarnica", None))
        self.L30.setText(QCoreApplication.translate("ZaglavljeTab", u"30 Lokacija robe", None))
        self.L1.setText(QCoreApplication.translate("ZaglavljeTab", u"1 Deklaracija", None))
        self.L3.setText(QCoreApplication.translate("ZaglavljeTab", u"3 Obrasci", None))
        self.L4.setText(QCoreApplication.translate("ZaglavljeTab", u"4 Tovarni listovi", None))
        self.L5.setText(QCoreApplication.translate("ZaglavljeTab", u"5 Stavke", None))
        self.L6.setText(QCoreApplication.translate("ZaglavljeTab", u"6 Uk. paketa", None))
        self.L7.setText(QCoreApplication.translate("ZaglavljeTab", u"7 Ref.br", None))
        self.L9.setText(QCoreApplication.translate("ZaglavljeTab", u"9 Odgovorna zemlja / Podaci", None))
        self.L10.setText(QCoreApplication.translate("ZaglavljeTab", u"10 Zem.otp.", None))
        self.L11.setText(QCoreApplication.translate("ZaglavljeTab", u"11 Trgov.zem.", None))
        self.L12.setText(QCoreApplication.translate("ZaglavljeTab", u"12 Vrijednost", None))
        self.L13.setText(QCoreApplication.translate("ZaglavljeTab", u"13 CAP", None))
        self.L15_s.setText(QCoreApplication.translate("ZaglavljeTab", u"15 Dr\u017eava izvoza", None))
        self.L15_sifra.setText(QCoreApplication.translate("ZaglavljeTab", u"15 \u0160ifra", None))
        self.L17_sifra_naslov.setText(QCoreApplication.translate("ZaglavljeTab", u"17 \u0160ifra", None))
        self.L16.setText(QCoreApplication.translate("ZaglavljeTab", u"16 Dr\u017eava porijekla", None))
        self.L17_drzava.setText(QCoreApplication.translate("ZaglavljeTab", u"17 Dr\u017eava odredi\u0161ta", None))
        self.L20.setText(QCoreApplication.translate("ZaglavljeTab", u"20 Uslovi isporuke", None))
        self.L22.setText(QCoreApplication.translate("ZaglavljeTab", u"22 Valuta i iznos", None))
        self.L23.setText(QCoreApplication.translate("ZaglavljeTab", u"23 Kurs", None))
        self.L24.setText(QCoreApplication.translate("ZaglavljeTab", u"24 Vrsta trans.", None))
        self.I_tr_1.setText(QCoreApplication.translate("ZaglavljeTab", u"0,00", None))
        self.L_tr_1.setText(QCoreApplication.translate("ZaglavljeTab", u"prevoz do granice", None))
        self.L_brutto.setText(QCoreApplication.translate("ZaglavljeTab", u"brutto", None))
        self.I_tr_2.setText(QCoreApplication.translate("ZaglavljeTab", u"0,00", None))
        self.L_tr_2.setText(QCoreApplication.translate("ZaglavljeTab", u"osiguranje", None))
        self.I_tr_3.setText(QCoreApplication.translate("ZaglavljeTab", u"0,00", None))
        self.L_tr_3.setText(QCoreApplication.translate("ZaglavljeTab", u"ost.tro\u0161kovi / dodaci", None))
        self.L_netto.setText(QCoreApplication.translate("ZaglavljeTab", u"netto", None))
        self.I_tr_4.setText(QCoreApplication.translate("ZaglavljeTab", u"0,00", None))
        self.L_tr_4.setText(QCoreApplication.translate("ZaglavljeTab", u"un. zavisni tro\u0161kovi", None))
        self.I_tr_5.setText(QCoreApplication.translate("ZaglavljeTab", u"0,00", None))
        self.L_tr_5.setText(QCoreApplication.translate("ZaglavljeTab", u"popusti", None))
        self.L_radni.setText(QCoreApplication.translate("ZaglavljeTab", u"radni mod\n"
"po vrij.", None))
        self.L48.setText(QCoreApplication.translate("ZaglavljeTab", u"48 odgo\u0111eno pla\u0107anje", None))
        self.L49.setText(QCoreApplication.translate("ZaglavljeTab", u"49 identifikacija skladi\u0161ta", None))
        self.L_pr_sifra.setText(QCoreApplication.translate("ZaglavljeTab", u"\u0160ifra", None))
        self.L_pr_naziv.setText(QCoreApplication.translate("ZaglavljeTab", u"Naziv", None))
        self.L_pr_datum.setText(QCoreApplication.translate("ZaglavljeTab", u"Datum", None))
        pass
    # retranslateUi

